server:
  port: 8081

spring:
  profiles:
    active: dev

---
server:
  port: 8082
spring:
  config:
    activate:
      on-profile: dev

---
server:
  port: 8083
spring:
  config:
    activate:
      on-profile: test
